### ISSUE TITLE
i' band magnitude error missing?

### ISSUE THREAD

**Issue by boada** [mommermi/photometrypipeline#14]
Calibrating the i' band it can't seem to find the associated magnitude error. I printed all of the fields in the catalog, and `e_imag` is missing. See below.

> * extract sources from 1 images using aperture radius 3.68px
> 29183 sources extracted from frame Hilt3i.fits
> 
> ----- run photometric calibration
> 
> (27627, 25) (sources, columns) read from Hilt3i.fits
> query Vizier for SDSS-R9 at   6.979/ +64.104 in a 0.79 deg radius no data available from SDSS-R9
> 0 sources downloaded from SDSS-R9
> query Vizier for APASS9 at   6.979/ +64.104 in a 0.79 deg radius 1309 sources retrieved.
> 1309 sources downloaded from APASS9
> <TableColumns names=('ident','ra.deg','dec.deg','e_ra.deg','e_dec.deg','Vmag','e_Vmag','Bmag','e_Bmag','gmag','e_gmag','rmag','e_rmag','imag','i_gmag','_RAJ2000','_DEJ2000')>
> Traceback (most recent call last):
>   File "/home/boada/Projects/photometrypipeline/pp_run", line 392, in <module>
>     fixed_aprad, source_tolerance)
>   File "/home/boada/Projects/photometrypipeline/pp_run", line 276, in run_the_pipeline
>     diagnostics=True)
>   File "/home/boada/Projects/photometrypipeline/pp_calibrate.py", line 421, in calibrate
>     max_sources=2e4, display=display)
>   File "/home/boada/Projects/photometrypipeline/pp_calibrate.py", line 124, in create_photometrycatalog
>     cat['e_'+filtername+'mag'] > mag_accuracy)
>   File "/home/boada/Projects/photometrypipeline/catalog.py", line 101, in __getitem__
>     return self.data[ident]
>   File "/home/boada/.local/lib/python2.7/site-packages/astropy/table/table.py", line 1196, in __getitem__
>     return self.columns[item]
>   File "/home/boada/.local/lib/python2.7/site-packages/astropy/table/table.py", line 109, in __getitem__
>     return OrderedDict.__getitem__(self, item)
> KeyError: 'e_imag'

**Comment by boada** [comment]
It's probably a typo on line 369 of `catalog.py`

`self.data.rename_column('e_i_mag', 'i_gmag')`

should be                                   

`self.data.rename_column('e_i_mag', 'e_imag')`

**Comment by mommermi** [comment]
yep, just found the same thing. Let me do a quick push.
