### ISSUE TITLE
Pillow now required?

### ISSUE THREAD

**Issue by boada** [mommermi/photometrypipeline#18]
The latest merge breaks my installation. 

> Traceback (most recent call last):
>   File "/home/boada/Projects/photometrypipeline/pp_run", line 46, in <module>
>     import pp_prepare
>   File "/home/boada/Projects/photometrypipeline/pp_prepare.py", line 44, in <module>
>     import diagnostics as diag
>   File "/home/boada/Projects/photometrypipeline/diagnostics.py", line 38, in <module>
>     from scipy.misc import toimage # requires Pillow
> ImportError: cannot import name toimage

It seems this is *not* an optional requirement. Pillow is not listed as a *required* install in the documentation.

**Comment by mommermi** [comment]
Yes, I made a number of changes last week, one of which was to use pillow throughout ``diagnostics.py`` as I was running into segmentation faults using 20kx20k images.
I haven't had time to update the documentation but will do this as soon as possible.

**Comment by boada** [comment]
I've started running into these strange segmentation faults. My images are:
NAXIS1  =                14793 / NUMBER OF ELEMENTS ALONG THIS AXIS             
NAXIS2  =                14571 / NUMBER OF ELEMENTS ALONG THIS AXIS 

Guess I am going to need to update. Lame-o
