### ISSUE TITLE
Timeout on failed searches?

### ISSUE THREAD

**Issue by boada** [mommermi/photometrypipeline#22]
This happened to me today:

> query Vizier for SDSS-R9 at 281.695/ +45.777 in a 0.58 deg radius no data available from SDSS-R9
> 0 sources downloaded from SDSS-R9
> query Vizier for APASS9 at 281.695/ +45.777 in a 0.58 deg radius no data available from APASS9
> 0 sources downloaded from APASS9
> query Vizier for PANSTARRS at 281.695/ +45.777 in a 0.58 deg radius MAST does currently not allow for PANSTARRS catalog queries with radii larger than 0.5 deg; clip radius to 0.5 deg

And it just sits there. If it fails to download anything, it *should* just give up after some time.

**Comment by mommermi** [comment]
Done!
