### ISSUE TITLE
Issues installing Source Extractor and SCAMP in Linux/Ubuntu

### ISSUE THREAD

**Issue by upendrak** [mommermi/photometrypipeline#23]
Does anyone has the list of instructions for installing the above two softwares? I am struggling to install them in Ubuntu. Any help would be appreciated. Thanks

**Comment by towicode** [comment]
On ubuntu 16.10

I was able to install most of the pre-reqs through apt-get

```
apt-get update && apt-get install -y \
   build-essential \
   libssl-dev \
   libffi-dev \
   python-dev \
   git \
   python \
   sextractor \
   python-pip \
   wget \
   curl \
   libplplot-dev \
   libshp-dev \
   libcurl4-gnutls-dev \
   liblapack3 liblapack-dev liblapacke liblapacke-dev \
   libfftw3-3 libfftw3-dev libfftw3-single3 \
   libatlas-base-dev
```

Then to get SCAMP

1. Grab development scamp `wget https://cdn.rawgit.com/towicode/towicode.github.io/8d4d8670/scamp-trunk.r345.tar.gz` Note: This is rehosted but you can get the exact one from the main website.
2. unzip `gzip -dc scamp-* | tar xvf -`
3. Then install using make `cd trunk.r345 && ./configure --enable-threads && make && make install`

**Comment by upendrak** [comment]
@towicode Thank you so much. Everything worked great. I am closing the issue now.

**Comment by mommermi** [comment]
@towicode, thanks for the write-up! I you don't mind, I will put this in the docs.

**Comment by upendrak** [comment]
Sure. I am currently making a Dockerfile and post it here once i test it out thoroughly. I will do a PR once the Dockerfile is thoroughly tested. I also just realized that it was you that have requested that this tool be installed in CyVerse DE. I will let you know once this is done too. Thanks..

**Comment by towicode** [comment]
Here is my dockerfile.
https://hub.docker.com/r/toddwickizer/photometrypipeline-singularity/~/dockerfile/

**Comment by upendrak** [comment]
Thanks..
