### ISSUE TITLE
NameError: global name 'sex_output' is not defined

### ISSUE THREAD

**Issue by hlabathems** [mommermi/photometrypipeline#30]
----- derive optimium photometry aperture

* extract sources from 2 images using 20 apertures
ERROR: mscience0218.ldac seems to be empty; check LOG file if Source Extractor ran properly
ERROR: mscience0217.ldac seems to be empty; check LOG file if Source Extractor ran properly
Traceback (most recent call last):
  File "/Users/michaelhlabathe/photometrypipeline/pp_run", line 409, in <module>
    fixed_aprad, source_tolerance)
  File "/Users/michaelhlabathe/photometrypipeline/pp_run", line 252, in run_the_pipeline
    diagnostics=True)
  File "/Users/michaelhlabathe/photometrypipeline/pp_photometry.py", line 374, in photometry
    diagnostics=diagnostics)
  File "/Users/michaelhlabathe/photometrypipeline/pp_photometry.py", line 91, in curve_of_growth_analysis
    extraction = pp_extract.extract_multiframe(filenames, extractparameters)
  File "/Users/michaelhlabathe/photometrypipeline/pp_extract.py", line 268, in extract_multiframe
    output = pool.map(extract_singleframe, data)
  File "/Users/michaelhlabathe/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/michaelhlabathe/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
NameError: global name 'sex_output' is not defined

**Comment by mommermi** [comment]
can you do a `git pull` and try again? If the problem persists, can you go into `diagnostics/LOG` and search for `call Source Extractor as:`? The line that follows this snippet refers to the Source Extractor call. If you run that call separately in the terminal, what does it say?

**Comment by hlabathems** [comment]
It gives me this when I ran it separately 

sex -c /Users/michaelhlabathe/photometrypipeline/setup/vatt4k.sex 
-PHOT_APERTURES
4.0,4.84210526316,5.68421052632,6.52631578947,7.36842105263,8.21052631579,9.05263157895,9.89473684211,10.7368421053,11.5789473684,12.4210526316,13.2631578947,14.1052631579,14.9473684211,15.7894736842,16.6315789474,17.4736842105,18.3157894737,19.1578947368,20.0
 -BACKPHOTO_TYPE LOCAL  -DETECT_MINAREA 12.000000  -DETECT_THRESH
1.500000 -ANALYSIS_THRESH 1.500000  -CATALOG_NAME mscience0217.ldac 
-PARAMETERS_NAME
/Users/michaelhlabathe/photometrypipeline/setup/twentyapertures.sexparam
mscience0217.fits 

> WARNING: DETECT_MAXAREA keyword unknown 

> WARNING: RESCALE_WEIGHTS keyword unknown 

> WARNING: SATUR_KEY keyword unknown 

> WARNING: GAIN_KEY keyword unknown 

> WARNING: ASSOCCOORD_TYPE keyword unknown 

> WARNING: HEADER_SUFFIX keyword unknown 

> WARNING: PATTERN_TYPE keyword unknown 

----- SExtractor 2.5.0 started on 2017-11-03 at 09:26:56 with 1 thread 

Measuring from: "3552"  / 2032 x 2032 / 64 bits FLOATING POINT data 

> *Error* in WCSlib: Invalid linear transformation parameters

On 2017-11-03 06:13, Michael Mommert wrote:

> can you do a git pull and try again? If the problem persists, can you go into diagnostics/LOG and search for call Source Extractor as:? The line that follows this snippet refers to the Source Extractor call. If you run that call separately in the terminal, what does it say? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mommermi/photometrypipeline/issues/30#issuecomment-341619310
[2]

**Comment by mommermi** [comment]
Thanks! You are using an old version of Source Extractor (2.5.0), can you try the latext version (2.19.5)? That should fix your problem.

**Comment by hlabathems** [comment]
Running the latest version worked, thanks:)

On 2017-11-03 17:12, Michael Mommert wrote:

> Thanks! You are using an old version of Source Extractor (2.5.0), can you try the latext version (2.19.5)? That should fix your problem. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mommermi/photometrypipeline/issues/30#issuecomment-341731889
[2]
