### ISSUE TITLE
skycenter bug.

### ISSUE THREAD

**Issue by boada** [mommermi/photometrypipeline#31]
I'll post this here for completeness. 

On line https://github.com/mommermi/photometrypipeline/blob/bc33b68b4338be3d8a1aa203e0b279864c355c8c/toolbox.py#L197 the code is missing some cosines to deal with fields at really high declination. 

See http://spiff.rit.edu/classes/phys440/lectures/coords/coords.html for example.

**Comment by boada** [comment]
Here's a quick fix... 

Using line 197 as written... 

> In [71]: numpy.sqrt((old_div((max_ra - min_ra), 2.))**2 + (old_div((max_dec - min_dec), 
>    ...: 2.))**2)             
> Out[71]: 5.2578715121645629

or using astropy, which is already required for PP

> In [64]: from astropy.coordinates import SkyCoord
> In [65]: from astropy import units as u
> In [66]: c1 = SkyCoord(ra = max_ra, dec = max_dec, frame='icrs', unit='deg')
> In [67]: c2 = SkyCoord(ra = min_ra, dec = max_dec, frame='icrs', unit='deg')
> In [68]: c1.separation(c2)
> Out[68]: <Angle 1.0099576017358838 deg>

**Comment by mommermi** [comment]
Thanks for this report. I fixed the problem!
