### ISSUE TITLE
`pp_run all` doesn't find any files

### ISSUE THREAD

**Issue by mkelley** [mommermi/photometrypipeline#4]
Hi Michael,

`pp_run all` stops with `IOError: cannot find any data...`.  According to the documentation, it should walk through the directories and find all FITS files.  But according to the code, `-prefix` must be set in order for this to work: [pp_run#L353](/mommermi/photometrypipeline/blob/5b1c0995f066a21fd38353f899d7cbbaba1f7018/pp_run.py#L353).  I'm not sure which is the correct behavior (docs or code), so I'll let you take care of it.  At the same time, the call to `run_the_pipeline` on line 372 is missing the `source_tolerance` parameter.

Thanks,
msk

**Comment by mommermi** [comment]
Mike, 

the documentation seems to be unclear in that case: you actually have to use ``run -prefix <something> all``; the ``prefix`` option is required such that pp can distinguish the actual science images from other stuff. I will clarify the documentation in that point.

Thanks for catching the missing ``source_tolerance`` parameter. I added it and pushed the commit to origin/master.

Thanks for working on this! It's really useful to have somebody check all this stuff!

M

**Comment by mkelley** [comment]
Oops, shouldn't have closed that just yet.

Thanks again.

**Comment by mommermi** [comment]
Mike, this should be fixed now. ``pp_run all`` should now find and use all *.fits, *.fit, *.FITS, etc. files in the underlying directories with the ``-prefix`` parameter being optional.

Let me know if it works for you.

M

**Comment by mkelley** [comment]
Indeed it does.

Cheers,
msk
