### ISSUE TITLE
Failure when processing NOT data

### ISSUE THREAD

**Issue by Siltala** [mommermi/photometrypipeline#48]
Hi,

I'm trying to use photometrypipeline for analyzing an asteroid lightcurve (total of 195 observations taken with the NOT) and something seems to be going horribly wrong; as far as I can tell, the program does not manage to match any images with the Gaia catalogue and ends up crashing. Flat-field and bias corrections have been applied to the images and the edges of the filter have been trimmed out.

I'm not sure on what debug information you exactly need, but 
[here](https://gist.github.com/Siltala/b3d0e7fdbb7da9702b60bd5ca33e3e42)'s the terminal output of `pp_run *.fits &> pp_log.txt` (I notice a lot of NaN and zero values here?)
and [here](https://gist.github.com/Siltala/c902b695a5e367b42ad4428f588bdd3c) is the 'LOG' file outputted in the data folder.

I'm using the commits of #47 (to actually identify the correct filter) on top of latest master.
Do you have any pointers on how to get around this?  Let me know if you need more information (or example data files)

**Comment by mommermi** [comment]
Are you running this on a Mac? There seems to be an issue with SCAMP on newer versions of MacOS. If so, try using a different catalog in the registration step, e.g.,  `pp_register -cat 2MASS *fits`

**Comment by Siltala** [comment]
Yes, I'm using a mac. I tried with the 2MASS catalogue and the same error occurs (again none of them match the catalogue).
I'll try it on my Linux system just in case and see if it works better there.

**Comment by Siltala** [comment]
Interestingly, running photometrypipeline on Arch Linux also crashes but in a completely different manner (and much earlier). Terminal output for that one is [here](https://gist.github.com/Siltala/131c6c406be9ceb755f984426f9a5fb9).

**Comment by Siltala** [comment]
I noticed that my Arch Linux crash is probably the same as in #45 so that's an already reported bug.
Meanwhile, on Mac, I tested the example data included with photometrypipeline and it also fails in the registration process in the same way as the NOT data does.

**Comment by mommermi** [comment]
can you provide me a sample image somewhere online?

**Comment by Siltala** [comment]
Sure! Attaching an arbitrary example image from my lightcurve here.
[tfzALDd300134.zip](https://github.com/mommermi/photometrypipeline/files/4591846/tfzALDd300134.zip)

**Comment by Siltala** [comment]
I worked around bug #45 by fixing the disp format in catalog.py on my end (I have no idea what an actually reasonable format would be, so i havent submitted a PR for now) and can confirm that, with that bug/crash fixed, my data fails on Linux in the same way as it does on Mac (match succeeded for 0/195 images) so this doesn't look like a Mac specific bug.

**Comment by mommermi** [comment]
This sounds great, please submit a PR!

**Comment by mommermi** [comment]
closed as per PR #50

**Comment by Siltala** [comment]
Hi, to clarify, this is still a problem. There is a separate bug here on top of #45 (which is indeed fixed). In other words the issue  described here remains.
