### ISSUE TITLE
APASS9 to z' fails

### ISSUE THREAD

**Issue by boada** [mommermi/photometrypipeline#9]
Photometric calibration fails on the z' band.

> ----- run photometric calibration
> 
> (26152, 25) (sources, columns) read from Hilt3z.fits
> query Vizier for SDSS-R9 at   6.988/ +64.096 in a 0.82 deg radius no data available from SDSS-R9
> 0 sources downloaded from SDSS-R9
> query Vizier for APASS9 at   6.988/ +64.096 in a 0.82 deg radius 1403 sources retrieved.
> 1403 sources downloaded from APASS9
> ERROR: no transformation from APASS9 to z available
> Traceback (most recent call last):
>   File "/home/boada/Projects/photometrypipeline/pp_run", line 392, in <module>
>     fixed_aprad, source_tolerance)
>   File "/home/boada/Projects/photometrypipeline/pp_run", line 276, in run_the_pipeline
>     diagnostics=True)
>   File "/home/boada/Projects/photometrypipeline/pp_calibrate.py", line 421, in calibrate
>     max_sources=2e4, display=display)
>   File "/home/boada/Projects/photometrypipeline/pp_calibrate.py", line 107, in create_photometrycatalog
>     cat['_e_'+filtername+'mag'] > mag_accuracy)
>   File "/home/boada/Projects/photometrypipeline/catalog.py", line 101, in __getitem__
>     return self.data[ident]
>   File "/home/boada/.local/lib/python2.7/site-packages/astropy/table/table.py", line 1196, in __getitem__
>     return self.columns[item]
>   File "/home/boada/.local/lib/python2.7/site-packages/astropy/table/table.py", line 109, in __getitem__
>     return OrderedDict.__getitem__(self, item)
> KeyError: '_e_zmag'

**Comment by mommermi** [comment]
The problem is that there is no transformation between griBV to z band.
However, there is a transformation from 2MASS to UKIRT Z band (also known
as MKO Z). I am not sure if UKIRT Z is the same as SDSS z; if so, I could
implement that...

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  Michael Mommert, Research Associate
  Northern Arizona University, Department of Physics and Astronomy
  PO Box 6010 Flagstaff, AZ 86011
  michaelmommert.wordpress.com | +1-928-523-5595
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by boada** [comment]
Hmmm.. I'll look into the difference between UKIRT Z and SDSS z'.

**Comment by boada** [comment]
The UKIRT z' band is quite a bit different that the SDSS z' band. I suppose I'll just have to figure out some other way of getting my stuff calibrated for that band. Something that might be worth considering is PanSTARRS. They have released their 1st set of data, and they include an SDSS z'. It doesn't look like their catalog is available on ViZIER. I think it's on MAST.

http://archive.stsci.edu/panstarrs/search.php

With a quick look, I didn't see any way of remote SQL searches. But that doesn't mean it isn't there.

**Comment by mommermi** [comment]
There is an API to access the MAST data and I started working on a script to download Pan-STARRS data: https://michaelmommert.wordpress.com/2017/02/13/accessing-the-gaia-and-pan-starrs-catalogs-using-python/

However, the download takes forever and is limited to 0.5 deg radius queries. I was hoping that vizier would duplicate the Pan-STARRS catalog, but is probably not going to happen. I will look into this as I would like to use Pan-STARRS as a default photometric catalog in the future.

**Comment by boada** [comment]
This can be closed.
